spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/25_05_Spring?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password:
mybatis:
  type-aliases-package: com.example.demo.vo
  mapper-locations: classpath:/mappers/**/*.xml